### ISSUE TITLE
URGENT : Error 

### ISSUE THREAD

**Issue by spseon** [chatdoc-com/ChatDOC-API-Demo#23]
Hello,

We are using Chatdoc API to serve our customers.

Suddenly, it keeps returning error on Chatdoc API. We checked that the problem is not on our side. Also, regular Chatdoc also keeps returning error.

<img width="824" alt="스크린샷 2024-12-12 오전 11 54 02" src="https://github.com/user-attachments/assets/be3f4733-eec5-4ff3-97b3-14a6752c6669" />

<img width="812" alt="스크린샷 2024-12-12 오전 11 53 50" src="https://github.com/user-attachments/assets/bfc735bf-1365-4409-83e8-e4fb2746ccef" />

We need it to be resolved as soon as possible. Please get back to us as soon as possible.

Thank you.

**Comment by Ronalci** [comment]
> Hello,
> 
> We are using Chatdoc API to serve our customers.
> 
> Suddenly, it keeps returning error on Chatdoc API. We checked that the problem is not on our side. Also, regular Chatdoc also keeps returning error.
> 
> <img alt="스크린샷 2024-12-12 오전 11 54 02" width="824" src="https://private-user-images.githubusercontent.com/166799964/394989950-be3f4733-eec5-4ff3-97b3-14a6752c6669.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5NzMwMzMsIm5iZiI6MTczMzk3MjczMywicGF0aCI6Ii8xNjY3OTk5NjQvMzk0OTg5OTUwLWJlM2Y0NzMzLWVlYzUtNGZmMy05N2IzLTE0YTY3NTJjNjY2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMlQwMzA1MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YzE3NGFmMzhkZjEwZWRjZjhmN2EzNDcxMzRlNDkxNDEyNWM4ZTNhZjBlOGMzMGZkZTVlNmIxMzJhYzA4ZGE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.aOscVL8U4R-VaPruLCQTNhd-63hHbn3qLVWcNDrpTO4"> <img alt="스크린샷 2024-12-12 오전 11 53 50" width="812" src="https://private-user-images.githubusercontent.com/166799964/394989909-bfc735bf-1365-4409-83e8-e4fb2746ccef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5NzMwMzMsIm5iZiI6MTczMzk3MjczMywicGF0aCI6Ii8xNjY3OTk5NjQvMzk0OTg5OTA5LWJmYzczNWJmLTEzNjUtNDQwOS04M2U4LWU0ZmIyNzQ2Y2NlZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMlQwMzA1MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMWQ0M2ViZmE0NDIzNGQyODI1NTg0NWU3ZTkzZjRhYTZhZGE0NDY5MjE3NGNiOGVhNGY5MmY1NTdlOTc3YWY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.HsUELRDHWpA8eAoSt_1eCCqhsxPwqjRbaGv2n3VvQWw">
> We need it to be resolved as soon as possible. Please get back to us as soon as possible.
> 
> Thank you.

Hello Spseon!

Thank you very much for your feedback! We have noticed fluctuations with OpenAI's API, as indicated on their status page https://status.openai.com/. Your experience might be related to this issue. We are working diligently to resolve the problem. Please try again later.

Best regards,
